name: Mediatek_filogic_padavanonly

on:
  workflow_dispatch:
    inputs:   
      device:
        description: 'Select the build device'
        required: true
        default: 'CETRON CT3003'
        type: choice
        options:
          - 'ABT ASR3000'
          - 'CETRON CT3003'
          - 'CMCC A10'
          - 'CMCC RAX3000M eMMC'
          - 'CMCC RAX3000M NAND'
          - 'GL.iNet GL-MT3000'
          - 'H3C NX30PRO'
          - 'Imou LC-HX3001'
          - 'JCG Q30'
          - 'KONKA KOMI A31'
          - 'Livinet ZR-3020'
          - 'MediaTek 360 T7'
          - 'MediaTek 360 T7 (with 108M ubi)'
          - 'MediaTek CLT R30B1'
          - 'MediaTek CLT R30B1 (with 112M ubi)'
          - 'Xiaomi Mi Router AX3000T'
          - 'Xiaomi Mi Router AX3000T (stock layout)'
          - 'Xiaomi Mi Router WR30U (stock layout)'
          - 'Xiaomi Mi Router WR30U (112M UBI layout)'
          - 'Xiaomi Mi Router WR30U (stock layout)'
          - 'GL.iNet GL-MT6000 '
          - 'TP-Link TL-XDR6086'
          - 'TP-Link TL-XDR6088'
          - 'Xiaomi Redmi Router AX6000'
          - 'Xiaomi Redmi Router AX6000'
      lan_addr:
        description: 'Setting default LAN address'
        required: true
        default: '10.0.0.1'
        type: string
  
jobs:
  Build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      continue-on-error: true
      uses: actions/checkout@main
      with:
        path: ZeroWrt-Action

    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'        
        echo build_dir="/builder" >> "$GITHUB_ENV"
        
    - name: Free disk space
      uses: oppen321/actions@free-disk
      with:
        build-mount-path: /builder
        
    - name: Build System Setup
      uses: oppen321/actions@openwrt-build-setup 

    - name: Compile OpenWrt
      working-directory: /builder
      id: compile
      continue-on-error: true
      run: |    
        curl -sS -O https://git.kejizero.online/zhao/files/raw/branch/main/hanwckf_mt7981.sh && chmod +x hanwckf_mt7981.sh && ./hanwckf_mt7981.sh
        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

    - name: Prepare Firmware Files
      working-directory: /builder
      run: |
        mkdir -p rom
        cp -a openwrt/bin/targets/mediatek/mt7981/*.bin rom/
        cp -a openwrt/bin/targets/mediatek/mt7981/*.tar rom/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hanwckf_mt798x
        path: ${{ env.build_dir }}/rom/*

    - name: Create release
      continue-on-error: true
      uses: ncipollo/release-action@v1
      with:
        name: R${{ env.DATE }} for ${{ env.FIRMWARE_TAG }}
        allowUpdates: true
        tag: ${{ env.FIRMWARE_TAG }}
        commit: master
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.build_dir }}/rom/*
        body: |
          **This is OpenWrt Firmware for ${{ env.FIRMWARE_TAG }}**
          ### ğŸ“’ å›ºä»¶ä¿¡æ¯
          - ğŸ’» å¹³å°æ¶æ„: Mediatek_filogic_hanwckf_mt7981
          - âš½ å›ºä»¶æºç : ${{ env.REPO_URL }}
          - ğŸ’ æºç åˆ†æ”¯: ${{ env.REPO_BRANCH }}
          - ğŸš€ å†…æ ¸ç‰ˆæœ¬: 5.4.284
          - ğŸŒ é»˜è®¤åœ°å€: 10.0.0.1
          - ğŸ”‘ é»˜è®¤å¯†ç : password
